POST http://localhost:5000/libros
Content-Type: application/json

{
  "titulo": "Flask Avanzado",
  "descripcion": "libro intensivo de desarrollo con Flask",
  "autor": "Tu Nombre",
  "isbn": "1234567890",
  "categoria": "Desarrollo",
  "anio_publicacion": 2025,
  "estado": "Disponible"
}
###
POST http://localhost:5000/login
Content-Type: application/x-www-form-urlencoded

email=notienesdescuento@gmail.com&password=test2