### Editar un libro (POST)

# Simular POST con nuevos datos del libro

PUT http://localhost:5000/localhost:5000/libros/1
Content-Type: application/json

{
  "titulo": "Libro actualizado",
  "descripcion": "Nueva descripción actualizada"
}
